### ISSUE TITLE
accessing G property

### ISSUE THREAD

**Issue by anurat** [SaFrMo/vue3-boardgame#3]
Not sure if this is related to this vue plugin, but need some help.

![image](https://user-images.githubusercontent.com/2355534/133032231-555508e2-e4a8-4fd1-a444-cfd31a097511.png)

```
G {{ G }}
<br>
G.cells {{ G.cells }}

```

When I tried to print out G, it showed correctly with cells property, but when I tried to access cells, I got undefined.
Strange behavior, do you know what's wrong here?

**Comment by anurat** [comment]
Okay, so It's gotta be `G.value.cells` instead.
Sorry about this.

**Comment by SaFrMo** [comment]
Haha no worries, I did the exact same thing! 😄
